---
title: "Weekly Update - 11/27/2019"
author: "Quentin Goss `quentingoss0323@floridapoly.edu`"
output:
    html_document:
        df_print: paged
---

```{r include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
```

```{r message=FALSE, warning=FALSE}
library("tidyverse")
library("latex2exp")
library("caret")
```


```{r}
reward = 500
tau = 1

read.vehicle.csv <- function(file){
    data <-  read.csv(
        file=file,
        header=TRUE,
        sep=',',
        colClasses=c(
            'id' = 'character',
            'source' = 'character',
            'destination' = 'character',
            'shortest.path.length' = 'double',
            'diversion.path.length' = 'double',
            'sample.time' = 'double',
            'sample.time.diff' = 'double',
            'target.id' = 'character'
            )
        )
    return(as_tibble(data))
}

mutate.utility <- function(veh.data) {
    veh.data <- veh.data %>%
        mutate(utility = reward * (1 - exp(-(sample.time.diff/tau))) - (abs(diversion.path.length) - abs(shortest.path.length)))
    return(veh.data)
}

read.target.csv <- function(file){
    data <- read.csv(
        file=file,
        header=TRUE,
        sep=',',
        colClasses = c(
            'target' = 'character',
            'vehicle' = 'character',
            'time' = 'double',
            'dt' = 'double'
        )
    )
    data <- data %>% as_tibble()
    data <- data %>% 
        within(dt[dt==Inf] <- time[dt==Inf])
    return(as_tibble(data))
    
}

calc.Tcov <- function(tar.data,M){
    targets <- unique(tar.data$target)
    Tcov <- targets %>% 
        map_dbl(
            function(tr) {
                tdata <- tar.data %>% 
                    filter(target == tr)
                tdata <- tdata[,c("time","dt")]
                N <- nrow(tdata)
                sumT <- sum(tdata)
                tdata.norm <- tdata %>% 
                    preProcess(method = c("range")) %>%
                    predict(tdata)
                # P <- norm(tar.data_$dt) %>% 
                #     map_dbl(
                #         function(time) {
                #             p <- time/sumT
                #             return(p * log(1/p))
                #         }
                #     ) 
                # return(1/log(N+1)*sumP)
            }
        )
    return(Tcov)
}

```


```{r}
bl <- read.target.csv("baseline10/targets.csv")
M <- 10
targets <- unique(bl$target)
Tcov <- targets %>% 
    map_dbl(
        function(tr) {
            tdata <- bl %>% 
                filter(target == tr) %>% 
                select(dt)
            tdata.norm <- tdata %>% 
                preProcess(method = c("range")) %>% 
                predict(tdata)
            tdata.norm[nrow(tdata.norm) + 1,] <- mean(tdata.norm$dt)
            tdata.norm <- tdata.norm %>% 
                mutate(sample = dt*log(1/dt))
            print(tdata.norm)
        }
    )
```


<!-- ```{r} -->
<!-- n.tar <- c(10,25,50,100) -->
<!-- baseline.utility <- n.tar %>%  -->
<!--     map_dbl( -->
<!--         function(M) { -->
<!--             paste0("baseline",M,"/targets.csv") %>%  -->
<!--                 read.target.csv() %>%  -->
<!--                 calc.utility(M) -->
<!--         } -->
<!--     ) -->
<!-- nash.utility <- n.tar %>%  -->
<!--     map_dbl( -->
<!--         function(M) { -->
<!--             paste0("nash",M,"/targets.csv") %>%  -->
<!--                 read.target.csv() %>%  -->
<!--                 calc.utility(M) -->
<!--         } -->
<!--     ) -->
<!-- utility <- tibble( -->
<!--         M = n.tar, -->
<!--         baseline = baseline.utility, -->
<!--         harish = nash.utility -->
<!--     ) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- ggplot() + -->
<!--     labs(title="Harish vs Baseline (One Assignment)",x="M (# Targets)",y=TeX("Utility  $U_p = \\frac{1}{M} \\sum_{i=1}^M T_{cov}^i$"),color="Method") + -->
<!--     scale_color_manual(labels = c("Baseline","Harish"), values = c("red","blue")) + -->
<!--     theme_bw() + -->
<!--     geom_point(aes(x = utility$M, y = utility$baseline, color = "red")) + -->
<!--     geom_line(aes(x = utility$M, y = utility$baseline, color = "red")) + -->
<!--     geom_point(aes(x = utility$M, y = utility$harish, color = "blue")) + -->
<!--     geom_line(aes(x = utility$M, y = utility$harish, color = "blue")) -->

<!-- ``` -->

